### ISSUE TITLE
Ao3rdr Disappears

### ISSUE THREAD

**Issue by terribleriddle** [darthkrallt/AO3rdr#38] opened 2016-09-03 23:53 UTC
**Browser:** Firefox 48.0.2

**Other active addons:** 
NoScript
Ghostery
Adblock Plus
Mute Tab
BetterPrivacy
NewXKit

**Problem:** Ao3rdr will not appear when browsing Ao3 even when it is active and up to date. Uninstalling and reinstalling does not fix the problem. What does fix the problem is hitting the debug and then reload buttons, then reloading firefox completely. This fix only lasts for that session.

**Added Note:** Sorry if this is the wrong place for this. I simply followed your directions on your page. If you want I can remove this.

**Comment by darthkrallt** [comment] 2016-09-04 01:54
Nah, it's a great place for it, thank you!! I would love to follow up with you on this issue to try to figure out what is causing it.

**Comment by terribleriddle** [comment] 2016-09-04 01:58
Sure thing. If there's any more information I can give you feel free to let me know.

**Comment by darthkrallt** [comment] 2016-09-05 23:57
Hmm, yeah I can reproduce it off the bat with 48.2.0 (on linux anyways), yikes :(

Annoyingly, it presents as fine on the Developer version and the mobile beta, which is what I typically use in development and day to day (respectively). If you have any error logs around the issue that would be helpful, but not entirely necessary since I can reproduce it.

When did you first notice this problem?

**Comment by darthkrallt** [comment] 2016-09-06 00:46
Ok, I think I have a fix.

I've built a test version of the add on as a signed extension. This means that it's:
a) not listed on the Firefox store
b) Won't have access to the same data as the "real" listed version
c) Has been run through mozilla's automated tests and was signed, so is installable

If you could test this version for me and see if it works that would be wonderful. I want to make sure it fixes your problem.

https://github.com/darthkrallt/AO3rdr/blob/feature/js_tests/ao3rdr_test-1.2.5-an%2Bfx.xpi

After downloading it, you can install it like so (notice the `AO3rdr-test` name):

![screenshot from 2016-09-05 17 41 40](https://cloud.githubusercontent.com/assets/10494377/18258750/86432ee4-7390-11e6-8e9b-ca52cc84d53c.png)


This is just a test version, so after you've checked it, I recommend uninstalling it.

However, if you are wary of installing a random extension file from a rando on the internet, I totally understand :)  I will move forward with the assumption that since I could reproduce the bug, and that this seems to fix it, that we are good to go.

**Comment by darthkrallt** [comment] 2016-09-09 06:28
Ok, version 1.3 is live on firefox addons page, and as far as I can tell it is not disappearing. Thank you so much for reporting this bug, I am marking it as resolved.

Any more issues, please contact me again and I will be happy to try to resolve them for you.

**Closed by darthkrallt** 2016-09-09 06:28 UTC
Labels: bug
